<a href="https://colab.research.google.com/github/SukhmanpreetKaurManes/Linear-Algebra/blob/main/mathematics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Linear Algebra**

In [ ]:
import numpy as np

In [ ]:
v=np.array([1,2,3,4,5,5,6])
v1=np.array([5,6,4,6,7,8,9])
v2=np.array([2,6,7])
print(type(v2))
print(v+v1)
#vector operations can be performed on vectors of similar length
#print(v+v2)
print(v-v1)
print(v*v1)
print(v/v1)
print(v%v1)
print(v**v1)

<class 'numpy.ndarray'>
[ 6  8  7 10 12 13 15]
[-4 -4 -1 -2 -2 -3 -3]
[ 5 12 12 24 35 40 54]
[0.2        0.33333333 0.75       0.66666667 0.71428571 0.625
 0.66666667]
[1 2 3 4 5 5 6]
[       1       64       81     4096    78125   390625 10077696]


In [ ]:
print(5*v)

[ 5 10 15 20 25 25 30]


In [ ]:
print(np.dot(v,v1))
#print(np.dot(v,v2))

182


In [ ]:
#print(np.cross(v,v1))
#print(np.cross(v,v2))
#incompatible dimensions
v3=np.array([1,2,3])
v4=np.array([4,5])
v5=np.array([1,2])
#print("first ans-->",np.cross(v3,v4))
print("Second ans-->",np.cross(v2,v3))
#print("Third ans-->",np.cross(v4,v5))
# cross product requires vectors with 3 numbers

Second ans--> [ 4  1 -2]


The dot product of two vectors results in a scalar (a single number).

It measures how much two vectors align in the same direction.

Formula:

A.B=AB cos theta



The cross product of two vectors results in a vector that is perpendicular to both.

It measures the area of the parallelogram formed by the two vectors.
A*B=AB sin theta

In [ ]:
determinant=np.linalg.det(np.array([[1,2],[3,4]]))
print(determinant)

-2.0000000000000004


In [ ]:
magnitude=np.linalg.norm(v)
print(magnitude)

10.770329614269007


In [ ]:
normalized_vector=v/np.linalg.norm(v)
print(normalized_vector)

[0.09284767 0.18569534 0.27854301 0.37139068 0.46423835 0.46423835
 0.55708601]


A normalized vector is a vector that has been scaled to have a magnitude (length) of 1, while maintaining its original direction. This process is called vector normalization

In [ ]:
squared_vector=v**2
print(squared_vector)

[ 1  4  9 16 25 25 36]


In [ ]:
#orthogonal  vectors are those having determinant 0

In [ ]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(type(A))
print(A+B)
print(A-B)
print(A*B)
print(A/B)

<class 'numpy.ndarray'>
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [ ]:
c_mul=np.dot(A,B)
print(c_mul)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
C=np.array([[1,2],[3,4]])
inv_C=np.linalg.inv(C)
print(inv_C)

[[-2.   1. ]
 [ 1.5 -0.5]]


The inverse of a matrix is a matrix that, when multiplied by the original matrix, results in the identity matrix.Not all matrices have an inverse. A matrix must:

Be square (same number of rows and columns).

Be non-singular, meaning its determinant is not zero

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


An eigenvalue is a scalar that represents how much an eigenvector is stretched or shrunk during a linear transformation. If a matrix
𝐴 acts on a vector 𝑣
, and the result is a scaled version of 𝑣
, then the scaling factor is the eigenvalue 𝜆
.

Mathematically, this is expressed as:

𝐴𝑣=𝜆𝑣
𝐴
 is a square matrix,

𝑣
 is an eigenvector,

𝜆
 is the eigenvalue.

An eigenvector is a nonzero vector that remains in the same direction after a linear transformation, though its magnitude may change. It is associated with an eigenvalue and satisfies the equation above.

In [ ]:
A_transpose=np.transpose(A)
print("Transpose:\n",A_transpose)

Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#Angle between vectors
import numpy as np
a=np.array([1,2])
b=np.array([2,3])
dot_product=np.dot(a,b)
norm_a=np.linalg.norm(a)
norm_b=np.linalg.norm(b)
cos_theta=dot_product/(norm_a*norm_b)
theta_rad=np.arccos(cos_theta)
angle_deg=np.degrees(theta_rad)                        #1 radian = 180° / π ≈ 57.2958°
print("Dot product:",dot_product)
print("Norm of a:",norm_a)
print("Norm of b:",norm_b)
print("Cosine of theta:",cos_theta)
print("Angle in radians:",theta_rad)
print("Angle in degrees:",angle_deg)


Dot product: 8
Norm of a: 2.23606797749979
Norm of b: 3.605551275463989
Cosine of theta: 0.9922778767136677
Angle in radians: 0.12435499454676072
Angle in degrees: 7.125016348901757


In [ ]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 0], [0, 1], [1, 1]])
result = A @ B
print("Matrix Multiplication Result:\n", result)

Matrix Multiplication Result:
 [[ 4  5]
 [10 11]]


In [ ]:
print(np.allclose(A.T.T, A))

True


A.T is the transpose of matrix A.

A.T.T is the transpose of the transpose, which brings you back to the original matrix A.

np.allclose() checks if two arrays are element-wise equal within a tolerance

In [ ]:
C = np.array([[5, 6], [7, 8], [9, 10]])
print("Original shape:", C.shape, "Transposed shape:", C.T.shape)

Original shape: (3, 2) Transposed shape: (2, 3)


In [ ]:
A = np.array([[2, 3], [1, 4]])
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: 5.000000000000001


In [ ]:
if det_A != 0:
    A_inv = np.linalg.inv(A)
    print("Inverse of A:\n", A_inv)

Inverse of A:
 [[ 0.8 -0.6]
 [-0.2  0.4]]


In [ ]:
B = np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]])
print("Rank of B:", np.linalg.matrix_rank(B))

Rank of B: 1


In [ ]:
print("Check Identity:\n", np.round(A @ A_inv))

Check Identity:
 [[ 1. -0.]
 [ 0.  1.]]


In [ ]:
A = np.array([[2, 3], [1, 2]])
b = np.array([8, 5])

In [ ]:
# 1. Solve the system
x = np.linalg.solve(A, b)
print("Solution x:", x)
#np.linalg.solve() is used to solve systems of linear equations

Solution x: [1. 2.]


In [ ]:
# 2. Modify A and b to test for no solution (inconsistent system)
A_inconsistent = np.array([[1, -1], [2, -2]])
b_inconsistent = np.array([2, 5])
try:
    x = np.linalg.solve(A_inconsistent, b_inconsistent)
except np.linalg.LinAlgError as e:
    print("No solution:", e)

No solution: Singular matrix


In [ ]:
augmented_matrix = np.column_stack((A_inconsistent, b_inconsistent))
print("Rank of A:", np.linalg.matrix_rank(A_inconsistent))
print("Rank of augmented matrix:", np.linalg.matrix_rank(augmented_matrix))

Rank of A: 1
Rank of augmented matrix: 2


In [ ]:
import numpy as np

A = np.array([[2, 4, 6], [1, 3, 5], [3, 7, 9]])
rank = np.linalg.matrix_rank(A)
print("Rank of A:", rank)


Rank of A: 3


In [ ]:
B = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
det_B = np.linalg.det(B)
print("Determinant of B:", round(det_B, 2))


Determinant of B: 1.0


In [ ]:
C = np.array([[4, 7], [2, 6]])
det_C = np.linalg.det(C)
print("Determinant of C:", det_C)
if det_C != 0:
    inv_C = np.linalg.inv(C)
    print("Inverse of C:\n", inv_C)
else:
    print("Matrix is singular.")


Determinant of C: 10.000000000000002
Inverse of C:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [ ]:
D = np.array([[3, 1], [2, 4]])
inv_D = np.linalg.inv(D)
print("Inverse of D:\n", inv_D)


Inverse of D:
 [[ 0.4 -0.1]
 [-0.2  0.3]]


In [ ]:
identity_check = D @ inv_D
print("D * D⁻¹:\n", identity_check)


D * D⁻¹:
 [[1. 0.]
 [0. 1.]]


In [ ]:
E = np.array([[1, 2], [2, 4]])  # Determinant = 0 (rows are multiples)
try:
    inv_E = np.linalg.inv(E)
    print(inv_E)
except np.linalg.LinAlgError:
    print("Matrix E is singular and not invertible.")


Matrix E is singular and not invertible.


In [ ]:
A = np.array([[2, 1], [1, 3]])
x = np.array([4, 5])
Tx = A @ x
print("T(x):", Tx)


T(x): [13 19]


In [ ]:
E = np.array([[1, 2], [2, 4]])  # Determinant = 0 (rows are multiples)
try:
    inv_E = np.linalg.inv(E)
    print(inv_E)
except np.linalg.LinAlgError:
    print("Matrix E is singular and not invertible.")


Matrix E is singular and not invertible.


In [ ]:
A = np.array([[2, 1], [1, 3]])
x = np.array([4, 5])
Tx = A @ x
print("T(x):", Tx)


T(x): [13 19]


In [ ]:
I = np.identity(3)
v = np.array([1, 2, 3])
result = I @ v
print("I * v =", result)


I * v = [1. 2. 3.]


In [ ]:
Z = np.zeros((3, 3))
x = np.array([5, 6, 7])
print("Z * x =", Z @ x)


Z * x = [0. 0. 0.]


In [ ]:
M = np.array([[2, 0], [0, 3]])
eigenvalues, eigenvectors = np.linalg.eig(M)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]
